FROM openjdk:17

RUN gradle bootJar

EXPOSE 3000

ARG JAR_FILE=build/libs/EticketUz-0.0.1-SNAPSHOT.jar

ADD ${JAR_FILE} eticket-uz

ENTRYPOINT ["java","-jar", "eticket-uz"]

FROM openjdk:11
WORKDIR /my-project
CMD ["./gradlew", "clean", "bootJar"]
COPY build/libs/*.jar app.jar

EXPOSE 8080
ENTRYPOINT ["java",  "-jar", "/app.jar"]
